spring.datasource.url=jdbc:postgresql://localhost:5432/snake_game
spring.datasource.username=postgres
spring.datasource.password=Latita123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true